# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'PGR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PGR
   pod 'Kingfisher'
  target 'PGRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PGRUITests' do
    # Pods for testing
  end

end
